-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 10:07:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Fut5al
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Fut5al` ;

-- -----------------------------------------------------
-- Schema Fut5al
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Fut5al` DEFAULT CHARACTER SET utf8 ;
USE `Fut5al` ;

-- -----------------------------------------------------
-- Table `Fut5al`.`Atleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fut5al`.`Atleta` ;

CREATE TABLE IF NOT EXISTS `Fut5al`.`Atleta` (
  `Email` VARCHAR(45) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `DataDiNascita` DATE NULL,
  `Residenza` VARCHAR(45) NULL,
  `RuoloPreferito` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Cod_UNIQUE` (`ID` ASC) VISIBLE,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fut5al`.`Campetto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fut5al`.`Campetto` ;

CREATE TABLE IF NOT EXISTS `Fut5al`.`Campetto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tariffa` VARCHAR(45) NOT NULL,
  `Città` VARCHAR(45) NOT NULL,
  `Valutazione` VARCHAR(45) NOT NULL,
  `Agibilita` TINYINT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fut5al`.`Gestore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fut5al`.`Gestore` ;

CREATE TABLE IF NOT EXISTS `Fut5al`.`Gestore` (
  `Email` VARCHAR(45) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Campetto_ID` INT NOT NULL,
  UNIQUE INDEX `Cod_UNIQUE` (`ID` ASC) VISIBLE,
  PRIMARY KEY (`Email`, `Campetto_ID`),
  INDEX `fk_Gestore_Campetto1_idx` (`Campetto_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Gestore_Campetto1`
    FOREIGN KEY (`Campetto_ID`)
    REFERENCES `Fut5al`.`Campetto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fut5al`.`Gioca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fut5al`.`Gioca` ;

CREATE TABLE IF NOT EXISTS `Fut5al`.`Gioca` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Atleta_Email` VARCHAR(45) NOT NULL,
  `Partita_ID` INT NOT NULL,
  `StatoInvito` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Atleta_has_Partita_Partita1_idx` (`Partita_ID` ASC) VISIBLE,
  INDEX `fk_Atleta_has_Partita_Atleta1_idx` (`Atleta_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_has_Partita_Atleta1`
    FOREIGN KEY (`Atleta_Email`)
    REFERENCES `Fut5al`.`Atleta` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_has_Partita_Partita1`
    FOREIGN KEY (`Partita_ID`)
    REFERENCES `Fut5al`.`Partita` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fut5al`.`Partita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fut5al`.`Partita` ;

CREATE TABLE IF NOT EXISTS `Fut5al`.`Partita` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `Ora` INT NOT NULL,
  `StatoPartita` VARCHAR(45) NOT NULL,
  `Campetto_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Campetto_ID`),
  INDEX `fk_Partita_Campetto1_idx` (`Campetto_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Partita_Campetto1`
    FOREIGN KEY (`Campetto_ID`)
    REFERENCES `Fut5al`.`Campetto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
